spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/aipm
    driver-class-name: org.postgresql.Driver
    username: aipm
    password: aipm_dev_password
  sql:
    init:
      mode: never
  flyway:
    enabled: false

jwt:
  private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCF4JSSG+m5uaLQJ+kEQxdj8IQfI1Dlmh5ixup01a5eOfufSjLPgPSQRERgbVcmamjPov6g0O1FIgyQd+0MWkFHu7+cyJkz+9dQj5wNDW2xDAf8OY5ghfqR9llZOBzJnQEtEUlSYfYWCZibufUqAjOZiqR/oybr7jUCD2fnfooAut7+209/EX3KoGILK+iqN7DBcQP3kKebwALvrSBbonWnjI0VpBbszgfoGq8IQkAR+J2igeJcbRc2xvSjG1OGQ7wt7p+iVYqFHDBEz/EluACpA6z4HY/EDfD2wtjMuGAddeWFLVQPnY/sseL6jNMug7S7BpTvv6oaUuC2zuEGLBk3AgMBAAECggEAEIwoQQEDPCoWVj1An369cuRlKEYgtyh8DgCBNUy+HzZyhAdTTXOmhvhxLSwGpCBt8RA4Ad+hHDTvsaGpIqg7PmcV8YaX7SV5QSNnCfP5dXNDv2jL0OFujcER3SXC5SarYQsscWrbVHD+NG1hQL6B6z4IRCCB7JKGaclGsgXhf+JrbjeybsT0+zMjDW989H7ou93qqRGjL8aWjWa2WJdk+euQ5R3b6mjt7f4FRY9KhdpXRkU7NTzrNxCHnUBOjo0V41WdTwfXePjDgHLtmkC+e08poYoFoybKugPKptWeO1pKni2b6LX9N2KpE7YJ/4NjsI70AIgBKKkj4yh3CNuTJQKBgQC3ORRK6TxWgkLDtGP1sXRiTyNM5zqj39yMHboYZD2p9DIWhritNCQoFzTBz15q1bhdF9XHN55Q3xR1VBHe6tkzBIylXlE8IO/6UcTRmOGGYn0fU8h5CCF28m2EEMTr7rt9O3mczZYu2X6LhhOZ+j4QulVC1htwYnymokBrF7KhFQKBgQC7Dc/4/PDcgUt0YjxgwtInD3ntQ225fEdh5jbb7w8J8tOed5KflIPAFs43UBmymAvRmIu6vWYTWAFrjEk4eJnY7hx6ZToQE3uZKQYIlbkcbcGS4bNW0ceJXcTqdxRdwtnCKvH0hqhuKaBzvmOl1npZFuexFVvteH63eLYFgm+sGwKBgCBmSo1Yox/VFwNOceKvh5oezmo59WenHXP1icPobfMQyI6tMhkGwGIKgHzJM7QGqPxlS5tX3XoFiLOaszJNKy1XX5uaixjr5iPIs9owg6jk36VbhnbIlkpXYkBZSslBxQvHKaEtxaHxOexoQC0ZUEJbANq5y85azBoXVPbbEO5lAoGBAIgOOui7aqKo9O45iftDmcJJkoEOm5/gErfV0K9WihTNaDmKdb7XMqGktOgsvhRWXbpdf70biESnrZjBmHyX1CeiwloQiRQqZ6t22GmkJdnUx4kD3ANZYQ68gr+cT9cHJIcD36vhyl8erhOiNy7n+2QTsgDvLUdkbp8bESKexoVjAoGAIAwBzxJk6FmRI6sN14ruCk5EBEeNtxPz/7vOlc3lmn7nS6R4d65N/zryGNu7nrY4jTVGWp1yGhZNmsyuOTl103iuYfE9rZS/qMza3kZkOSgJn1FOeAEd/BhJAlvDv2U08NDPUnegOPKNwazvTJK0AUQikZ9s/87DOhBWXf6D5Y0=
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAheCUkhvpubmi0CfpBEMXY/CEHyNQ5ZoeYsbqdNWuXjn7n0oyz4D0kEREYG1XJmpoz6L+oNDtRSIMkHftDFpBR7u/nMiZM/vXUI+cDQ1tsQwH/DmOYIX6kfZZWTgcyZ0BLRFJUmH2FgmYm7n1KgIzmYqkf6Mm6+41Ag9n536KALre/ttPfxF9yqBiCyvoqjewwXED95Cnm8AC760gW6J1p4yNFaQW7M4H6BqvCEJAEfidooHiXG0XNsb0oxtThkO8Le6folWKhRwwRM/xJbgAqQOs+B2PxA3w9sLYzLhgHXXlhS1UD52P7LHi+ozTLoO0uwaU77+qGlLgts7hBiwZNwIDAQAB

logging:
  level:
    com.ai_pm: DEBUG
