spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
  flyway:
    enabled: false
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: 5672

jwt:
  public-key: ${JWT_PUBLIC_KEY}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.ai_pm: INFO
